# Generated by Django 2.2.1 on 2021-01-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Counter', 'Counter'), ('Kitchen', 'Kitchen'), ('Ordinary', 'Ordinary')], default='Ordinary', max_length=10),
        ),
    ]
