# Generated by Django 2.2.1 on 2021-01-14 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_unique_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unique_number',
            field=models.UUIDField(default=uuid.UUID('567ea65b-4908-4226-9f16-ef205c9ccc64'), editable=False),
        ),
    ]
